import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';
import { ArrowDown, ArrowUp, ArrowUpDown, Eye, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';

type Props = { products: any; categories: { id: number; name: string }[]; filters: Record<string, any> };

export default function Products({ products, categories, filters }: Props) {
    const [search, setSearch] = useState(filters.search ?? '');
    const query = (extra: Record<string, any> = {}) => ({ search: filters.search, category_id: filters.category_id, status: filters.status, sort: filters.sort, direction: filters.direction, per_page: filters.per_page, ...extra });
    const visit = (extra: Record<string, any>) => router.get('/dashboard/products', query(extra), { preserveState: true, preserveScroll: true, replace: true });
    const sort = (field: string) => visit({ sort: field, direction: filters.sort === field && filters.direction === 'asc' ? 'desc' : 'asc', page: 1 });
    const remove = (id: number, title: string) => { if (window.confirm(`Delete ${title}? This action cannot be undone.`)) router.delete(`/dashboard/products/${id}`, { preserveScroll: true, onSuccess: () => toast.success('Product deleted successfully.') }); };
    const SortIcon = ({ field }: { field: string }) => filters.sort !== field ? <ArrowUpDown className="ml-1 inline h-4 w-4 opacity-40" /> : filters.direction === 'asc' ? <ArrowUp className="ml-1 inline h-4 w-4" /> : <ArrowDown className="ml-1 inline h-4 w-4" />;

    return <><Head title="Products" /><div className="flex flex-1 flex-col gap-5 p-4 lg:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-bold tracking-tight">Products</h1><p className="text-muted-foreground">Manage the catalog and publishing status.</p></div><Button asChild><Link href="/dashboard/products/create"><Plus className="mr-2 h-4 w-4" /> Add product</Link></Button></div>
        <div className="flex flex-col gap-3 rounded-lg border bg-card p-4 lg:flex-row"><form className="flex flex-1 gap-2" onSubmit={(event) => { event.preventDefault(); visit({ search, page: 1 }); }}><Input type="search" placeholder="Search title, SKU, article number..." value={search} onChange={(event) => setSearch(event.target.value)} /><Button type="submit" variant="secondary"><Search className="mr-2 h-4 w-4" /> Search</Button></form><select className="h-9 rounded-md border border-input bg-transparent px-3 text-sm" value={filters.category_id ?? ''} onChange={(event) => visit({ category_id: event.target.value || undefined, page: 1 })}><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><select className="h-9 rounded-md border border-input bg-transparent px-3 text-sm" value={filters.status ?? ''} onChange={(event) => visit({ status: event.target.value || undefined, page: 1 })}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select><select className="h-9 rounded-md border border-input bg-transparent px-3 text-sm" value={filters.per_page ?? 10} onChange={(event) => visit({ per_page: event.target.value, page: 1 })}><option value="10">10 / page</option><option value="25">25 / page</option><option value="50">50 / page</option></select></div>
        <div className="overflow-hidden rounded-lg border bg-card"><div className="w-full overflow-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/40"><tr><Header label="Product" field="title" sort={sort} icon={<SortIcon field="title" />} /><Header label="Article no." field="art_no" sort={sort} icon={<SortIcon field="art_no" />} /><th className="p-4 font-medium">Category</th><th className="p-4 font-medium">Status</th><Header label="Updated" field="updated_at" sort={sort} icon={<SortIcon field="updated_at" />} /><th className="p-4 text-right font-medium">Actions</th></tr></thead><tbody>{products.data.length === 0 ? <tr><td colSpan={6} className="p-10 text-center text-muted-foreground">No products match the current filters.</td></tr> : products.data.map((product: any) => <tr key={product.id} className="border-b last:border-0 hover:bg-muted/30"><td className="p-4"><Link href={`/dashboard/products/${product.id}`} className="font-medium hover:underline">{product.title}</Link><div className="text-xs text-muted-foreground">{product.sku || 'No SKU'}</div></td><td className="p-4 text-muted-foreground">{product.art_no}</td><td className="p-4">{product.category?.name ?? 'Uncategorized'}</td><td className="p-4"><Badge variant={product.is_active ? 'default' : 'secondary'}>{product.is_active ? 'Active' : 'Inactive'}</Badge>{product.is_featured && <Badge variant="outline" className="ml-2">Featured</Badge>}</td><td className="p-4 text-muted-foreground">{new Date(product.updated_at).toLocaleDateString()}</td><td className="p-4"><div className="flex justify-end gap-1"><Button variant="ghost" size="icon" asChild><Link href={`/dashboard/products/${product.id}`}><Eye /><span className="sr-only">View {product.title}</span></Link></Button><Button variant="ghost" size="icon" asChild><Link href={`/dashboard/products/${product.id}/edit`}><Pencil /><span className="sr-only">Edit {product.title}</span></Link></Button><Button variant="ghost" size="icon" onClick={() => remove(product.id, product.title)}><Trash2 className="text-destructive" /><span className="sr-only">Delete {product.title}</span></Button></div></td></tr>)}</tbody></table></div></div>
        <div className="flex flex-col justify-between gap-3 text-sm text-muted-foreground sm:flex-row sm:items-center"><span>Showing {products.from || 0} to {products.to || 0} of {products.total} products</span><div className="flex flex-wrap gap-2">{products.links.map((link: any, index: number) => <Button key={index} size="sm" variant={link.active ? 'default' : 'outline'} disabled={!link.url} onClick={() => link.url && router.get(link.url, query(), { preserveState: true, preserveScroll: true })} dangerouslySetInnerHTML={{ __html: link.label }} />)}</div></div>
    </div></>;
}

function Header({ label, field, sort, icon }: { label: string; field: string; sort: (field: string) => void; icon: React.ReactNode }) { return <th className="cursor-pointer p-4 font-medium hover:bg-muted/70" onClick={() => sort(field)}>{label}{icon}</th>; }

Products.layout = { breadcrumbs: [{ title: 'Dashboard', href: '/dashboard' }, { title: 'Products', href: '/dashboard/products' }] };