import { Head, Link, router } from '@inertiajs/react';
import { ArrowLeft, Pencil, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

export default function ShowProduct({ product }: { product: any }) {
    const remove = () => { if (window.confirm(`Delete ${product.title}? This action cannot be undone.`)) router.delete(`/dashboard/products/${product.id}`); };
    return <><Head title={product.title} /><div className="flex flex-1 flex-col gap-6 p-4 lg:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex items-start gap-4"><Button variant="ghost" size="icon" asChild><Link href="/dashboard/products"><ArrowLeft /></Link></Button><div><div className="mb-2 flex flex-wrap gap-2"><Badge variant={product.is_active ? 'default' : 'secondary'}>{product.is_active ? 'Active' : 'Inactive'}</Badge>{product.is_featured && <Badge variant="outline">Featured</Badge>}</div><h1 className="text-2xl font-bold tracking-tight">{product.title}</h1><p className="text-muted-foreground">{product.art_no}{product.sku ? ` · ${product.sku}` : ''}</p></div></div><div className="flex gap-2"><Button variant="outline" asChild><Link href={`/dashboard/products/${product.id}/edit`}><Pencil className="mr-2 h-4 w-4" /> Edit</Link></Button><Button variant="destructive" onClick={remove}><Trash2 className="mr-2 h-4 w-4" /> Delete</Button></div></div>
        <div className="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(260px,1fr)]"><div className="space-y-6"><section className="rounded-lg border bg-card p-6"><h2 className="mb-4 text-lg font-semibold">Description</h2><p className="whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{product.desc || product.short_desc || 'No description provided.'}</p></section><section className="rounded-lg border bg-card p-6"><h2 className="mb-4 text-lg font-semibold">Variants</h2><Detail label="Material" value={product.material} /><Detail label="Gender" value={product.gender} /><Detail label="Fit" value={product.fit} /><Detail label="Sizes" value={product.sizes?.join(', ')} /><Detail label="Colors" value={product.colors?.join(', ')} /></section></div><aside className="space-y-6"><section className="rounded-lg border bg-card p-6"><h2 className="mb-4 text-lg font-semibold">Catalog details</h2><Detail label="Category" value={product.category?.name} /><Detail label="Slug" value={product.slug} /><Detail label="Article number" value={product.art_no} /><Detail label="SKU" value={product.sku} /><Detail label="Created" value={new Date(product.created_at).toLocaleString()} /><Detail label="Updated" value={new Date(product.updated_at).toLocaleString()} /></section>{product.thumbnail && <section className="rounded-lg border bg-card p-6"><h2 className="mb-4 text-lg font-semibold">Thumbnail</h2><img src={product.thumbnail} alt={product.title} className="aspect-square w-full rounded-md object-cover" /></section>}</aside></div>
    </div></>;
}

function Detail({ label, value }: { label: string; value?: string | null }) { return <div className="flex justify-between gap-4 border-b py-3 text-sm last:border-0"><span className="text-muted-foreground">{label}</span><span className="text-right font-medium">{value || 'Not set'}</span></div>; }

ShowProduct.layout = { breadcrumbs: [{ title: 'Dashboard', href: '/dashboard' }, { title: 'Products', href: '/dashboard/products' }, { title: 'Product details', href: '#' }] };